### ISSUE TITLE
Gnome 43

### ISSUE THREAD

**Issue by lakoliu** [mmai/Current_screen_only_on_window_switcher#14]
First of all, I love this extension! Not having it is one of my biggest pain points when using a Windows machine.

Any chance it will be coming soon to Gnome 43? I'm using the Fedora 37 beta and this is the only thing I'm missing. Thanks!

**Comment by MSmaili** [comment]
any update on this?

**Comment by lakoliu** [comment]
As a workaround, you can install the extension manually by downloading the source code and then just change the `shell-version` list in the `metadata.json` file to include `43`.
