### ISSUE TITLE
Extension not working on Pop OS 22.04

### ISSUE THREAD

**Issue by yassine-cc** [mmai/Current_screen_only_on_window_switcher#16]
I'm on Pop os, and for some reason the extension is not working for me, i still see all the windows from all monitors when i alt tab, i have no idea if this is specific to Pop OS

**Comment by yassine-cc** [comment]
I am having the same issue

**Comment by my4ng** [comment]
The problem seems to be that Pop Shell overrides the change. You can turn it off in extension manager, and afterwards this works as expected but of course the window tiling functionalities are lost.
