### ISSUE TITLE
upstream status

### ISSUE THREAD

**Issue by carlocastoldi** [mmai/Current_screen_only_on_window_switcher#18]
Is there any issue/MR open upstream to discuss an eventual upstream of this extension?

It seems like a feature that doesn't disrupts GNOME's design, but rather enhance it

**Comment by mmai** [comment]
Hi @carlocastoldi. I didn't found one on https://gitlab.gnome.org/GNOME/gnome-shell/-/issues. 

I am reluctant to open one myself. I agree it enhances the design, this is why I made this extension, but it is still a matter of preferences, maybe some users like to be able to switch to any application regardless of the screen they are running on.

Also, I unfortunately would not have the time to do the merge myself : as I've not yet contributed to the upstream gnome shell project, it would mean learning the upstream code, discovering and following the contribution & validation process, etc.

**Comment by carlocastoldi** [comment]
I also have looked into the mutter repository and found no issues with similar references.

I understand your opinion and the reason why you are reluctant to open an issue yourself. Do you reckon it would be a bad idea if I opened a feature request without being able to work on it?

**Comment by mmai** [comment]
No at all, I think it's fine. You are not expected to be able to implement the feature request you are proposing
