### ISSUE TITLE
alt-tab dialog-window doesn't appear on second monitor

### ISSUE THREAD

**Issue by jdeut** [mmai/Current_screen_only_on_window_switcher#2]
It would be great that if alt-tab is pressed on the second monitor, that the alt-tab dialog also appears on the second monitor.

**Comment by DamienBth** [comment]
:+1: I totally agree with nichtleiter, this extension works well (thanks for that), but it would be a lot better if the dialog was on the current screen. Or at least on all screen.

**Comment by mmai** [comment]
That's fixed thanks to a contribution by @casperbiering

**Comment by DamienBth** [comment]
I am on Gnome 3.28.4, the modification of @casperbiering didn't work but helped me for making it work:
I had to get the file https://raw.githubusercontent.com/mmai/Current_screen_only_on_window_switcher/fade7b5439966689b30ee2a0ef66d1c9afe9ef20/extension.js
And modified line 13:
global.display.get_current_monitor() => global.screen.get_current_monitor()

Thanks !
